### ISSUE TITLE
[tern.mmrm] [UAT] manually run and test example code in `R/fit_mmrm.R`

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.mmrm#15]
# Motivation
`rtables` and `formatable` packages are taking care of var_labels from upstream. Some potential break changes in the example code

# ToDo

- [x] Manually run and test example code
- [x] If the example code fails, create a *BUG* reporting issue in `tern.mmrm` with title "[UAT] example code fails in `R/fit_mmrm.R` "
- [ ] If multiple errors, create multiple issues
- [x] If issues created, reference in the comment

# Definition of done

* test example code works
* BUG reporting issues reference created if testing example code fails
