### ISSUE TITLE
adapt to new `mmrm` package

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.mmrm#152]
After cran releases of tern, formatters and rtables, mmrm

- [x]  Align to the latest tern https://github.com/insightsengineering/tern/issues/990
- [x]  Align to the latest formatter https://github.com/insightsengineering/formatters/issues/175
- [x]  Align to the latest rtables https://github.com/insightsengineering/rtables/issues/696
- [x] new mmrm version

- todo 

- [x] update the description file
- [x] fixes/adaptations:
	- [x] `g_mmrm_diagnostic` to use the new `residuals` method instead of calculating residuals manually
	- [x] correct a test for weights
	- [x] fix `model.frame` usage
	- [x] new forest plot and table snapshots are ok too 
	- [x] be more general and reference `mmrm` documentation for the details of `fit_mmrm` (lose coupling)

**Comment by danielinteractive** [comment]
Hi @donyunardi , as discussed yesterday, let me have a first stab at this because we will need to change more things according to the new `mmrm` version on GitHub (0.3.5). Afterwards we can continue with general updates
