### ISSUE TITLE
[tern.mmrm] Code migration from tern

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/tern.mmrm#22]
# TODO

Move the following functions from tern to tern.mmrm

  - [x] [test-fit_mmrm.R](https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-fit_mmrm.R)
  - [x] [test-table_mmrmt01.R](https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-table_mmrmt01.R)
  - [x] [test-tabulate_mmrm.R](https://github.com/insightsengineering/tern/blob/main/tests/testthat/test-tabulate_mmrm.R)
  
  - [x] [fit_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/fit_mmrm.R)
  - [x] [g_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/g_mmrm.R)
  - [x] [tabulate_mmrm.R](https://github.com/insightsengineering/tern/blob/main/R/tabulate_mmrm.R)

Also see [Splitting mmrm from tern](https://github.com/insightsengineering/tern/issues/348)
